// Entry point. The imports below load every module (the order matters little: each one only declares things and
// registers listeners); the start-up that needs everything loaded — language, volumes, the base screen, the
// systems and the loop — runs at the bottom, after all of them.
import { setLang, defaultLang } from '../../engine/core/i18n.js';
import { applyLayout } from '../../engine/ui/touchlayout.js';
import { save, syncVolumes } from './js/system/save.js';
import { fsLabel, renderGuide } from './js/ui/hud.js';
import { showTab, baseTab } from './js/flow/game.js';
import '../../engine/core/util.js';
import '../../engine/core/store.js';
import '../../engine/core/dev.js';
import '../../engine/core/loop.js';
import '../../engine/core/world.js';
import '../../engine/core/i18n.js';
import '../../engine/audio/audio.js';
import '../../engine/audio/music.js';
import '../../engine/render/render.js';
import '../../engine/render/fx.js';
import '../../engine/world/tiles.js';
import '../../engine/world/projectiles.js';
import '../../engine/world/steer.js';
import '../../engine/ui/ui.js';
import '../../engine/ui/input.js';
import '../../engine/ui/touchlayout.js';
import './js/data/weapons.js';
import './js/data/viewmodels.js';
import './js/data/level.js';
import './js/data/enemies.js';
import './js/data/bosses.js';
import './js/data/biomes.js';
import './js/data/progress.js';
import './js/data/perks.js';
import './js/data/controls.js';
import './js/data/sfx.js';
import './js/data/music.js';
import './js/lang/ja.js';
import './js/lang/en.js';
import './js/system/text.js';
import './js/system/save.js';
import './js/system/rules.js';
import './js/flow/music.js';
import './js/world/render.js';
import './js/world/level.js';
import './js/world/entities.js';
import './js/actors/player.js';
import './js/actors/bosses/common.js';
import './js/actors/bosses/watcher.js';
import './js/actors/bosses/crusher.js';
import './js/actors/bosses/core.js';
import './js/actors/bosses/phantom.js';
import './js/actors/bosses/trinity.js';
import './js/actors/bosses/bastion.js';
import './js/ui/input.js';
import './js/ui/hud.js';
import './js/flow/game.js';
import './js/ui/share.js';
import './js/actors/enemies.js';
import './js/actors/bullets.js';
import { boot } from './js/flow/update.js';
import './js/dev/dev.js';

setLang(save.settings.lang || defaultLang());
syncVolumes();
fsLabel(); applyLayout(); renderGuide(); showTab(baseTab);
boot();
